In [1]:
import numpy as np
from random import randint
import numpy.ma as ma

In [2]:
a = np.zeros((1000, 1000), dtype='int')
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i][j] = randint(0, 10)
        
a

array([[ 4,  6,  7, ...,  5,  7,  2],
       [ 8,  2, 10, ...,  1,  1,  9],
       [ 3,  4,  4, ...,  8,  4,  2],
       ...,
       [ 1,  9,  3, ...,  8,  6,  2],
       [ 0, 10, 10, ...,  9,  7,  6],
       [ 2,  7,  1, ...,  7,  9,  8]])

In [3]:
rand_mask = np.zeros((1000, 1000), dtype='int')
for i in range(rand_mask.shape[0]):
    for j in range(rand_mask.shape[1]):
        rand_mask[i][j] = randint(0, 1)

rand_mask

array([[1, 1, 1, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 1, 1],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 1, 1]])

In [4]:
b = ma.masked_array(a, mask=rand_mask)
b

masked_array(
  data=[[--, --, --, ..., 5, --, 2],
        [8, 2, --, ..., 1, --, --],
        [3, --, 4, ..., --, --, --],
        ...,
        [1, --, --, ..., --, --, --],
        [0, 10, --, ..., 9, --, 6],
        [--, 7, 1, ..., --, --, --]],
  mask=[[ True,  True,  True, ..., False,  True, False],
        [False, False,  True, ..., False,  True,  True],
        [False,  True, False, ...,  True,  True,  True],
        ...,
        [False,  True,  True, ...,  True,  True,  True],
        [False, False,  True, ..., False,  True, False],
        [ True, False, False, ...,  True,  True,  True]],
  fill_value=999999)

In [5]:
print(a.mean())
print(b.mean())

4.997211
4.99537505535706


In [46]:
# we have mean of a = 4.997211 because we use all elements in matrix
a.sum()/(a.shape[0] * a.shape[1])

5.06

In [81]:
# we have mean of b = 4.99537505535706 because we use not all elements, but only elements that we have(empty cells we dont count)
print(b.sum()/(b.shape[0] * b.shape[1]))# it will be if we count all elements
print(b.sum()/b.count()) # it is when we use sum of elements and number of existing elements

2.16
4.909090909090909


In [126]:
c = np.full(shape=(1, 100), fill_value=range(100))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [129]:
d = np.tile(c, (100, 1))
print(d.shape)
print(d[:, 0])
print(d[:, 99])
print(d)

(100, 100)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99]
[[ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 ...
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]]
