In [4]:
import numpy as np
from random import randint
import numpy.ma as ma

In [39]:
a = np.zeros((10, 10), dtype='int')
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i][j] = randint(0, 10)
        
a

array([[ 3,  9,  8,  6,  9,  6,  9,  4,  3,  6],
       [ 5,  8,  9,  7, 10,  5,  4,  9,  5, 10],
       [10,  1,  6,  5,  9,  7,  8,  9,  7,  7],
       [ 6,  4,  0,  2,  3,  5,  4,  2,  9,  7],
       [ 5,  0,  3,  0,  1,  1,  5, 10,  0,  2],
       [ 3,  3,  3,  2,  1,  0,  9,  3,  7,  8],
       [ 9,  3,  6,  5, 10,  6,  7,  6,  6,  3],
       [ 6,  6,  0,  0,  3,  7,  0,  3,  1,  7],
       [ 2, 10,  8,  4,  2,  7,  4,  0,  5,  4],
       [ 8, 10,  0,  7,  0, 10,  4,  0,  5, 10]])

In [40]:
rand_mask = np.zeros((10, 10), dtype='int')
for i in range(rand_mask.shape[0]):
    for j in range(rand_mask.shape[1]):
        rand_mask[i][j] = randint(0, 1)

rand_mask

array([[1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1]])

In [80]:
b = ma.masked_array(a, mask=rand_mask)
b

masked_array(
  data=[[--, 9, --, 6, --, 6, --, 4, 3, --],
        [5, 8, 9, --, --, 5, --, 9, --, --],
        [10, --, 6, --, 9, --, --, 9, 7, 7],
        [6, 4, 0, 2, --, 5, --, --, --, --],
        [5, --, --, --, --, 1, --, 10, --, --],
        [3, --, 3, 2, 1, 0, --, --, --, --],
        [--, --, 6, --, 10, 6, --, --, --, --],
        [6, 6, --, 0, --, 7, 0, --, 1, 7],
        [--, --, --, --, --, --, 4, --, --, 4],
        [--, --, --, --, 0, --, --, 0, 5, --]],
  mask=[[ True, False,  True, False,  True, False,  True, False, False,
          True],
        [False, False, False,  True,  True, False,  True, False,  True,
          True],
        [False,  True, False,  True, False,  True,  True, False, False,
         False],
        [False, False, False, False,  True, False,  True,  True,  True,
          True],
        [False,  True,  True,  True,  True, False,  True, False,  True,
          True],
        [False,  True, False, False, False, False,  True,  True,  True,
         

In [42]:
print(a.mean())
print(b.mean())

5.06
4.909090909090909


In [46]:
# we have mean of a = 5.06 because we use all elements in matrix
a.sum()/(a.shape[0] * a.shape[1])

5.06

In [81]:
# we have mean of b = 4.909090909090909 because we use not all elements, but only elements that we have(empty cells we dont count)
print(b.sum()/(b.shape[0] * b.shape[1]))# it will be if we count all elements
print(b.sum()/b.count()) # it is when we use sum of elements and number of existing elements

2.16
4.909090909090909


In [126]:
c = np.full(shape=(1, 100), fill_value=range(100))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [129]:
d = np.tile(c, (100, 1))
print(d.shape)
print(d[:, 0])
print(d[:, 99])
print(d)

(100, 100)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99]
[[ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 ...
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]
 [ 0  1  2 ... 97 98 99]]
